In [1]:
import numpy as np
import cv2
from numpy import matrix as M
import matplotlib.pyplot as plt
import os

In [24]:
path = r'C:/Users/Aditya/Pictures/'
image_path = 'Lenna_(test_image).png'
original_image = cv2.imread(os.path.join(path , image_path))
gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)
cv2.imshow('original image', gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
gray_image

array([[162, 162, 162, ..., 170, 155, 128],
       [162, 162, 162, ..., 170, 155, 128],
       [162, 162, 162, ..., 170, 155, 128],
       ...,
       [ 43,  43,  50, ..., 104, 100,  98],
       [ 44,  44,  55, ..., 104, 105, 108],
       [ 44,  44,  55, ..., 104, 105, 108]], dtype=uint8)

In [8]:
## padding zeros to original image
## to keep size of the output image and original image same
def padding_zeros(image):
    y = np.zeros([image.shape[0]+2, image.shape[1]+2], dtype = np.uint8)
    for i in range(1, image.shape[0]+1):
        for j in range(1, image.shape[1]+1):
            y[i, j] = image[i-1, j-1]
    return y

In [9]:
new_image = padding_zeros(gray_image)
print(new_image)

[[  0   0   0 ...   0   0   0]
 [  0 162 162 ... 155 128   0]
 [  0 162 162 ... 155 128   0]
 ...
 [  0  44  44 ... 105 108   0]
 [  0  44  44 ... 105 108   0]
 [  0   0   0 ...   0   0   0]]


In [16]:
lpf = (1/9)*np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]], dtype = np.uint8)
print(lpf)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [17]:
## Convolution function
lpf_image = np.zeros([gray_image.shape[0], gray_image.shape[1]], dtype = np.uint8)
list_1 = []
for i in range(1, gray_image.shape[0]):
    for j in range(1, gray_image.shape[1]):
        #list_1.append(int(np.average((np.multiply(lpf, new_image[i-1:i+2, j-1:j+2]).flatten()))))
        lpf_image[i, j] = int(np.average((np.multiply(lpf, new_image[i-1:i+2, j-1:j+2]).flatten())))

In [25]:
cv2.imshow('low pass filtered image', lpf_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
hpf = np.array([[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]], dtype = np.uint8)
print(hpf)

[[255 255 255]
 [255   8 255]
 [255 255 255]]


In [19]:
hpf_image = np.zeros([gray_image.shape[0], gray_image.shape[1]], dtype = np.uint8)
list_1 = []
for i in range(1, gray_image.shape[0]):
    for j in range(1, gray_image.shape[1]):
        #list_1.append(int(np.average((np.multiply(lpf, new_image[i-1:i+2, j-1:j+2]).flatten()))))
        hpf_image[i, j] = int(np.average((np.multiply(hpf, new_image[i-1:i+2, j-1:j+2]).flatten())))

In [22]:
cv2.imshow('high pass filtered image', hpf_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.imshow('low pass filtered image', lpf_image)
cv2.imshow('high pass filtered image', hpf_image)
cv2.waitKey(0)
cv2.destroyAllWindows()