In [6]:
from PIL import Image
import numpy as np
import collections

def Count(count_list):
    count = dict()
    for item in count_list:
        if item in count:
           count[item] = count[item] + 1
        else :
            count[item] = 1
    return count

def CDF(dict_1):
    sum1 = 0
    cdf = dict()
    for i, j in count.items():
        sum1 = sum1 + count[i]
        cdf[i] = sum1
    return cdf

def calculate_histogram(dict_1):
    cdf_m = min(dict_1.values())
    L = 255
    hist = dict()
    for i, j in cdf.items():
        hist[i] = int(((dict_1[i] - cdf_m)/(699392 - cdf_m))*(L-1))
        
    return hist


img = Image.open(r'C:\Users\Aditya\Pictures\Unequalized_Hawkes_Bay_NZ.jpg')
img = img.convert('L')
img.show()
img2arr = np.array(img)
print(img2arr)
print(img2arr.shape)
image_shape = img2arr.shape

list_1 = []
list_2 = []
for i in range(image_shape[0]):
    for j in range(image_shape[1]):
        list_1.append(img2arr[i][j])
        list_2.append(img2arr[i][j])
        
list_1.sort()

count = Count(list_1)
cdf = CDF(count)

hist = calculate_histogram(cdf)

list_3 = []
for x in list_2:
    list_3.append(hist[x])
    
arr2img = np.array(list_3)
arr2img = arr2img.reshape(image_shape[0], image_shape[1])
img1 = Image.fromarray(arr2img)
img1.show()
img1.save('hist_equ_image.jpg')

[[127 145 149 ... 168 167 166]
 [165 152 143 ... 168 169 168]
 [171 145 140 ... 156 154 151]
 ...
 [147 132 134 ... 146 145 144]
 [146 130 132 ... 146 145 144]
 [145 128 129 ... 146 145 144]]
(683, 1024)


OSError: cannot write mode I as JPEG

In [3]:
#img2 = Image.open('hist_equ_image.png')

In [4]:
img2.show()