In [14]:
###########################################################################################################################
#                                                                                                                         #
#                                                Author : Aditya Kotasthane                                               #
#                                                                                                                         #
###########################################################################################################################


import numpy as np
import os

def Toboggan(input_matrix):
    gradient_matrix = np.array([[12, 14, 23, 13], [16, 11, 21, 18],  ## defining gradient matrix 
                       [21, 24, 23, 12], [12, 21, 20, 10]])          ## of shape (4, 4)
    
    print(gradient_matrix)
    print(input_matrix)
    
    shape = (input_matrix.shape[0]+2, input_matrix.shape[1]+2)
    gradient_matrix_padded = 255*np.ones(shape)
    output_matrix = np.zeros((input_matrix.shape[0], input_matrix.shape[1])) ## defining output matrix of size same as input
    input_matrix_padded = np.zeros(shape)  

    for i in range(0, input_matrix.shape[0]):                          ## padding 255 to toboggan matrix 
        for j in range(0, input_matrix.shape[1]):                      ## and padding zeros to input matrix
            gradient_matrix_padded[i+1, j+1] = gradient_matrix[i, j]
            input_matrix_padded[i+1, j+1] = input_matrix[i, j]

    print(gradient_matrix_padded)
    print(input_matrix_padded)
    
    for i in range(1, input_matrix.shape[0]+1):
        for j in range(1, input_matrix.shape[1]+1): 
            slice_matrix = input_matrix_padded[i-1:i+2, j-1:j+2]
            output_matrix[i-1, j-1] = slice_matrix[np.where(gradient_matrix_padded[i-1:i+2, j-1:j+2] == np.amin(gradient_matrix_padded[i-1:i+2, j-1:j+2]))]
      ## finding indices of smallest pixel among the neighbouring pixels
      ## and assigning the value of the input matrix pixel at that indices
      ## to the output matrix
    
    return output_matrix

In [15]:
input_matrix = np.array([[4, 4, 3, 2], [3, 7, 6, 1],
                        [2, 7, 6, 2], [0, 1, 0, 2]])

x = Toboggan(input_matrix)
print(x)

[[12 14 23 13]
 [16 11 21 18]
 [21 24 23 12]
 [12 21 20 10]]
[[4 4 3 2]
 [3 7 6 1]
 [2 7 6 2]
 [0 1 0 2]]
[[255. 255. 255. 255. 255. 255.]
 [255.  12.  14.  23.  13. 255.]
 [255.  16.  11.  21.  18. 255.]
 [255.  21.  24.  23.  12. 255.]
 [255.  12.  21.  20.  10. 255.]
 [255. 255. 255. 255. 255. 255.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 4. 4. 3. 2. 0.]
 [0. 3. 7. 6. 1. 0.]
 [0. 2. 7. 6. 2. 0.]
 [0. 0. 1. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[7. 7. 7. 2.]
 [7. 7. 7. 2.]
 [7. 7. 2. 2.]
 [0. 0. 2. 2.]]
